In this tutorial we're going to learn TensorFlow and Intro to Deep Learning.
TensorFlow is an open-source Machine Learning Library used for Deep Learning, and originally designed by Google.

What is a Tensor?
You can think of a tensor as a way of representing data into arrays (numbers), in which the numbers are going to be fed into a Artificial Neural Network to find patterns into those numbers. And of course, the ANN will output an array (numbers).


We're going to cover:
* Introduction to Tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using the @tf.function (a way to speed up your regular python functions)
* Using GPUs or TPUs to do fast numerical computing
* Exercise

In [13]:
import tensorflow as tf
print(tf.__version__)


2.3.0


In [14]:
#creating the first tensor using tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [15]:
#check the number of dimension of tensor (ndim stands for number of dimension)
scalar.ndim

0

In [16]:
#create a vector
vector = tf.constant([10,10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [17]:
#check the dimension of the vector
vector.ndim

1

In [20]:
#create a matrix
matrix = tf.constant([[10, 7],
                    [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [21]:
#ndim of the matrix
matrix.ndim

2

In [28]:
#create another matrix and this time specify the dtype
another_matrix = tf.constant([[4.,5.],
                  [2., 4.],
                  [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[4., 5.],
       [2., 4.],
       [8., 9.]], dtype=float16)>

In [29]:
another_matrix.ndim

2

In [30]:
#let's create a tensor
tensor = tf.constant([[[1, 3],
                      [2, 4]],
                     [[5, 8],
                     [6, 4]],
                     [[6, 5],
                     [2, 7]]], dtype= tf.int32)
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[1, 3],
        [2, 4]],

       [[5, 8],
        [6, 4]],

       [[6, 5],
        [2, 7]]])>

In [32]:
tensor.ndim

3

What we've created so far
* Scalar: a single number
* vector: a number with direction(e.g WindSpeed and direction)
* Matrix: a two dimensional array of numbers
* Tensor: an n-dimensional array of numbers(1-d is a scalar, 2-D is a matrix e.t.c) 

Creating tensors using `tf.Variable`

In [33]:
#creating the same tensor with tf.Variable() as above
changeable_tensor  = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [34]:
#changing the value in the changeable tensor
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7])>

### creating random tensors
Random tensors are tensors of some arbitiary size filled with Random numbers
setting the initial seed while initializing the random tensor won't make it a random tensor anymore

In [40]:
#creatomg a random tensor
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

#are they equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a Tensor

In [43]:
# shuffling the tensor (--this is useful when you want to shuffle your data so that the inherent data doesn't affect learning)
not_shuffled = tf.constant([[10, 7],
                           [3, 4],
                           [1, 5]])
shuffled = tf.random.shuffle(value= not_shuffled)
not_shuffled, shuffled

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 1,  5]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 1,  5],
        [ 3,  4]])>)

when training a NN, it initailizes itself with a random tensor. Now everytime you re-run the experiment u will be getting 
a different random tensor. Now if you want to produce, replicable experiments, then you have to use the Global seed operator
as well as operational level operator. 

In [46]:
tf.random.set_seed(42)
shuffled_1 = tf.random.shuffle(value= not_shuffled, seed=42)
shuffled_1  #u will get the same result each time you run this cell

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 1,  5]])>

### Other ways of Making Tensor

In [49]:
#creating a tensor of all ones
tf.ones([3,4], dtype= tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])>

In [51]:
#creating a tensor of all zeros
tf.zeros([5,6], dtype= tf.int32)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])>

### Turning Numpy arrays into Tensors
The main difference between a numpy array and a tensorflow tensor is that a tensor can be run into a GPU (much faster for numerical computing)

In [55]:
import numpy as np
numpy_a = np.arange(1, 25, dtype= np.int32)
tensor_a = tf.constant(value= numpy_a)
numpy_a, tensor_a



(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

In [56]:
#You can even change the shape of the tensor
tensor_a = tf.constant(value= numpy_a, shape=(2,3,4))
tensor_a

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

### Getting Information from Tensors

* Shape: The number of elements of each dimension in a tensor, Code tensor.shape
* Rank: --Think of it as dimension. Code tensor.ndim
* Axis or dimension: A particular dimension of a tensor. --think of it as a way of refferencing a particular item in a tensor code: tensor[0], tensor[:, -1], 
* Size: The total number of items in a tensor. Code: tf.size(tensor)

In [58]:
#create a rank 4 tensor
rank_4_tensor =  tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [59]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

### Indexing Tensors
Tensors can be indexed just like python lists

In [60]:
some_tensors = not_shuffled[0][1]
some_tensors

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [65]:
rank_2_tensor = tf.random.Generator.from_seed(42)
rank_2_tensor = tf.random.normal(shape=(3,2))
rank_2_tensor, tf.shape(rank_2_tensor)

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.55909735, -0.5347214 ],
        [ 2.3730333 , -1.5725931 ],
        [ 0.8055056 , -0.83387697]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2])>)

In [71]:
#Get the last item of our tensor
last_item = rank_2_tensor[2][-1]
last_item

#last item of each row
last_item1 = rank_2_tensor[: -1]
last_item1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.55909735, -0.5347214 ],
       [ 2.3730333 , -1.5725931 ]], dtype=float32)>

### One Hot Encoding Tensors


In [73]:
# create a list of indices
some_list = [2, 4, 5, 6]
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [74]:
#let's try to use words
some_words = ['Red', 'blue', 'yellow']
tf.one_hot(some_words, depth= 2)

InvalidArgumentError: Value for attr 'TI' of string is not in the list of allowed values: uint8, int32, int64
	; NodeDef: {{node OneHot}}; Op<name=OneHot; signature=indices:TI, depth:int32, on_value:T, off_value:T -> output:T; attr=axis:int,default=-1; attr=T:type; attr=TI:type,default=DT_INT64,allowed=[DT_UINT8, DT_INT32, DT_INT64]> [Op:OneHot]